# Generated by Django 4.2.3 on 2023-07-19 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starting_country", models.CharField(max_length=255)),
                ("destination_country", models.CharField(max_length=255)),
                ("shipping_channel", models.CharField(max_length=255)),
                ("shipping_time_range_min_days", models.IntegerField()),
                ("shipping_time_range_max_days", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PerWeightRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_weight_kg", models.FloatField()),
                ("max_weight_kg", models.FloatField()),
                ("per_kg_rate", models.FloatField()),
                (
                    "rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="quotes.rate",
                    ),
                ),
            ],
        ),
    ]
